types:
#  - test
  - mirror

#Audit:
#  script:
#    - brew audit --strict --online ./*.rb
#  type: test
#  tags:
#    - mac


Mirror to github.com:
  script:
    - if [ !git config remote.github.url > /dev/null ]; then
    -    git remote add github github-homebrew-tap:AarhusSubatom/homebrew-tap.git
    - fi
    - git push github master
  type: mirror
  tags:
    - mac
  only:
    - master