types:
#  - test
  - rewrite
  - mirror

#Audit:
#  script:
#    - brew audit --strict --online ./*.rb
#  type: test
#  tags:
#    - mac

Rewrite formular:
  script:
    - echo $FORMULA
    - echo $FORMULA_V
    - if [[ -v FORMULA ]] ; then
    -   ./update_formula.sh "$FORMULA.rb" $FORMULA_V
    -   cat "$FORMULA.rb"
    -   git add "$FORMULA.rb"
    -   git commit -m "Updated to $FORMULA.rb to version $FORMULA_V"
    -   git push git@git.kern.phys.au.dk:ausa/homebrew-tap.git master
    - fi
  type: rewrite
  tags:
    - linux
    - variables

Mirror to github.com:
  script:
    - if git config remote.github.url > /dev/null; then
    -    echo "Remote already defined"
    - else
    -    git remote add github github-homebrew-tap:AarhusSubatom/homebrew-tap.git
    -    echo "Remote defined"
    - fi
    - git push github "HEAD:master"
  type: mirror
  tags:
    - mac
  only:
    - master