types:
#  - test
  - rewrite
  - mirror

#Audit:
#  script:
#    - brew audit --strict --online ./*.rb
#  type: test
#  tags:
#    - mac

Rewrite formular:
  script:
    - echo $FORMULA
    - echo $FORMULA_V
    - if $FORMULA ; then
    -   ./update_formula.sh "$FORMULA.rb" $FORMULA_V
    - fi
    - cat "$FORMULA.rb"

Mirror to github.com:
  script:
    - if git config remote.github.url > /dev/null; then
    -    echo "Remote already defined"
    - else
    -    git remote add github github-homebrew-tap:AarhusSubatom/homebrew-tap.git
    -    echo "Remote defined"
    - fi
    - git push github "HEAD:master"
  type: mirror
  tags:
    - mac
  only:
    - master